name: Prettier-Standard

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  prettier:
    name: Prettier-Standard Check Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        version: '12.x'
    - run: yarn
    - run: yarn prettier-standard:check
